# Generated by Django 4.0.6 on 2023-01-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_age_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], default='M', max_length=5),
        ),
    ]
