# Generated by Django 4.0.6 on 2022-10-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('NPP01', models.IntegerField(default=0)),
                ('NPP02', models.IntegerField(default=0)),
                ('NPP03', models.IntegerField(default=0)),
                ('NPP04', models.IntegerField(default=0)),
                ('NPP05', models.IntegerField(default=0)),
                ('NPP06', models.IntegerField(default=0)),
                ('NPP07', models.IntegerField(default=0)),
                ('NPP08', models.IntegerField(default=0)),
                ('NPP09', models.IntegerField(default=0)),
                ('NPP10', models.IntegerField(default=0)),
                ('NPP11', models.IntegerField(default=0)),
                ('NPP12', models.IntegerField(default=0)),
                ('NPP13', models.IntegerField(default=0)),
                ('NPP14', models.IntegerField(default=0)),
                ('NPP15', models.IntegerField(default=0)),
                ('NPP16', models.IntegerField(default=0)),
                ('NPP17', models.IntegerField(default=0)),
                ('NPP18', models.IntegerField(default=0)),
                ('NPP19', models.IntegerField(default=0)),
                ('NPP20', models.IntegerField(default=0)),
            ],
        ),
    ]
