# Generated by Django 4.0.6 on 2022-10-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_remove_notice_user_list_notice_created_at_userlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='created_at',
        ),
        migrations.AddField(
            model_name='notice',
            name='user_list',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.DeleteModel(
            name='UserList',
        ),
    ]
