# Generated by Django 4.0.6 on 2022-10-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0005_notice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
