# Generated by Django 4.0.6 on 2022-10-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumptions', '0002_remove_supplementpost_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodconsumption',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
