# Generated by Django 4.0.6 on 2022-10-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_alter_recommendation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='type12',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
