# Generated by Django 4.0.6 on 2022-10-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_recommendation_type12'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
