# Generated by Django 4.0.6 on 2022-10-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_recommendation_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='hashtag',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
